### ISSUE TITLE
Text not visible

### ISSUE THREAD

**Issue by muisje** [jluttine/rofi-power-menu#1]
The menu launches with invisible text. The following line is a warning printed in the console when running this:

`pango_layout_set_markup_with_accel: Attribute 'allow_breaks' is not allowed on the <span> tag on line 1 char 96`

**Comment by jluttine** [comment]
@muisje Thanks for the report! Weird that I couldn't reproduce the issue. Maybe it's related to a version of some dependency. Anyway, `allow_breaks` was totally unnecessary, it was there by accident, so I just removed it. Could you check if it works for you now?
