### ISSUE TITLE
Wrong icons after updating to Nerd Fonts 3.0.0

### ISSUE THREAD

**Issue by xfzv** [jluttine/rofi-power-menu#19]
I'm using `JetBrainsMono Nerd Font`. After updating to [Nerd Fonts 3.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0), I'm getting wrong icons for Log out and Suspend:
![1](https://user-images.githubusercontent.com/78810647/235627400-48a431e1-c1dd-4e24-a31f-0ccf361d48bd.png)

Relevant part of my rofi configuration for rofi-power-menu:

```css
configuration {
  modi: "drun";
  font: "JetBrainsMono Nerd Font 10.5";
}
```

https://github.com/jluttine/rofi-power-menu/blob/e4cc444c109f8f924e10d9fcef0b15a7cf480585/rofi-power-menu#L33-L34

Same in Kitty with `JetBrainsMono Nerd Font` too.
![image](https://user-images.githubusercontent.com/78810647/235628098-c7dde158-3940-46bd-89de-a68939f9de3d.png)

Maybe they should be updated? this can help:

- Logout:
https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425#file-convert_unicode_nerdfont3-py-L773

- Suspend:
https://gist.github.com/mischw/78e8e42c2ebb1069560a2fc4573b1425#file-convert_unicode_nerdfont3-py-L1118

- Relevant issue in Nerd Font repo: https://github.com/ryanoasis/nerd-fonts/issues/1190

**Comment by jluttine** [comment]
Thanks for the report. I merged a PR that hopefully fixed this. Could you check whether the current version works for you or not?
