### ISSUE TITLE
Can't start on Gnome Shell

### ISSUE THREAD

**Issue by toketin** [jluttine/rofi-power-menu#2]
Hi, I'm trying it under Gnome Shell but I can't get it working since it's missing the `XDG_SESSION_ID` variable:

`/usr/bin/rofi-power-menu: riga 41: XDG_SESSION_ID: variabile non assegnata`

**Comment by jluttine** [comment]
What is the command you run? Does it fail immeditely on start or just fails to execute some of the choices? Does rofi itself work normally? For instance, does `rofi -show drun` work?

**Comment by jluttine** [comment]
Do you know why `XDG_SESSION_ID` isn't set? Is it so under Gnome Shell in general or just in your case?

**Comment by jluttine** [comment]
Could you confirm if it works for you now?

**Comment by toketin** [comment]
I confirm it's working now under i3wm thanks!
