### ISSUE TITLE
hyprlock support

### ISSUE THREAD

**Issue by CommanderGL** [jluttine/rofi-power-menu#32]

**Comment by Munsio** [comment]
Hyprlock does not listen to the `loginctl lock-session` command you need [Hypridle](https://wiki.hyprland.org/Hypr-Ecosystem/hypridle/) for that to work in combination.

Use the `general` configuration block from here: https://github.com/mhkarimi1383/hypr/blob/main/hypridle.conf to support hyprlock with the rofi power-menu and ignore the `listeners` if you don't need them.

**Comment by CommanderGL** [comment]
Got it! Fixed.
